### ISSUE TITLE
Decryption error

### ISSUE THREAD

**Issue by uksus70** [axuan25/kaa-docker#2]
Have you faced such an error on endpoint connection?
```
kaa_1 | 2016-04-11 09:55:23,089 [nioEventLoopGroup-3-4] INFO  o.k.k.s.t.h.t.n.DefaultHttpServerInitializer - DefaultServerInitializer Initializing Channel 494acf6d-c627-4e12-8e89-fa9770d1d59d connection from /46.173.5.37:61420
kaa_1 | 2016-04-11 09:55:23,124 [nioEventLoopGroup-3-4] ERROR o.k.k.s.t.h.t.n.DefaultExceptionHandler - Exception caught
kaa_1 | javax.crypto.BadPaddingException: Decryption error
kaa_1 |         at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:380) ~[na:1.8.0_77]
kaa_1 |         at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:291) ~[na:1.8.0_77]
kaa_1 |         at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_71]
kaa_1 |         at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_71]
kaa_1 |         at javax.crypto.Cipher.doFinal(Cipher.java:2165) ~[na:1.8.0_71]
kaa_1 |         at org.kaaproject.kaa.common.endpoint.security.MessageEncoderDecoder.decodeSessionKey(MessageEncoderDecoder.java:217) ~[endpoint-shared-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.common.endpoint.security.MessageEncoderDecoder.decodeData(MessageEncoderDecoder.java:209) ~[endpoint-shared-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.server.bootstrap.service.transport.BootstrapTransportService$BootstrapMessageHandler$1.decodeEncryptedRequest(BootstrapTransportService.java:237) ~[kaa-node-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.server.bootstrap.service.transport.BootstrapTransportService$BootstrapMessageHandler$1.decodeRequest(BootstrapTransportService.java:222) ~[kaa-node-0.8.1.jar:na]
kaa_1 |         at org.kaaproject.kaa.server.bootstrap.service.transport.BootstrapTransportService$BootstrapMessageHandler$1.run(BootstrapTransportService.java:163) ~[kaa-node-0.8.1.jar:na]
kaa_1 |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_77]
kaa_1 |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_77]
kaa_1 |         at java.lang.Thread.run(Thread.java:745) [na:1.8.0_77]
kaa_1 | 2016-04-11 09:55:23,124 [nioEventLoopGroup-3-4] WARN  o.k.k.s.t.h.t.netty.ResponseEncoder - Session [494acf6d-c627-4e12-8e89-fa9770d1d59d] got invalid HTTP response: DefaultFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: UnpooledUnsafeHeapByteBuf(ridx: 0, widx: 16, cap: 48))
kaa_1 | HTTP/1.1 500 Internal Server Error
kaa_1 | Content-Type: text/plain; charset=UTF-8
kaa_1 | Content-Length: 16
kaa_1 | Connection: close
```

**Comment by axuan25** [comment]
Dear Anthony,

I have not encountered this error. Has this been occurring to you while
only using the docker image?
I will have time to look into it in a day or two, only, unfortunately.

Best regards,
Christopher

Christopher Burroughs 歐陽軒
B.A. Asian Studies, Option I: China & Taiwan
University of California, Berkeley | 2014
+1-714-752-3340 | axuan@chrisplusplus.net

On Mon, Apr 11, 2016 at 2:01 PM, Anthony Serdyukov <notifications@github.com

**Comment by uksus70** [comment]
Yes, only in the docker. Afterwards I have deployed KAA on the host machine and it worked fine.
Here is my `docker-compose.yml`:
```
version: '2'
services:
  kaa_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=kaa
  kaa:
    build: kaa/0.8/
    depends_on:
      - kaa_db
      - mongo
      - zookeeper
    links:
      - "kaa_db:db"
    environment:
      - ZOOKEEPER_IP=zookeeper
      - JDBC_HOST=db
      - MONGODB_NODE_LIST=mongo:27017
      - NOSQL_DB_PROVIDER_NAME=mongodb
      - TRANSPORT_PUBLIC_INTERFACE
    ports:
      - "8080:8080"
      - "9888:9888"
      - "9889:9889"
      - "9997:9997"
      - "9999:9999"
  zookeeper:
    image: jplock/zookeeper
  mongo:
    image: mongo
```
